<a href="https://colab.research.google.com/github/Parikshith21/ML_LAB/blob/master/basics_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd

In [0]:
data=[1,2,3,4,21,6,5]

In [0]:
series=pd.Series(data)

In [0]:
series

0     1
1     2
2     3
3     4
4    21
5     6
6     5
dtype: int64

In [0]:
type(series)

pandas.core.series.Series

In [0]:
series=pd.Series(data,index=['a','b','c','d','f','g','h'])

In [0]:
series

a     1
b     2
c     3
d     4
f    21
g     6
h     5
dtype: int64

In [0]:
df=pd.DataFrame(data)

In [0]:
df

    0
0   1
1   2
2   3
3   4
4  21
5   6
6   5

In [0]:
dict={'b':['a1','a2','a3'],'count':[20,21,22]}

In [0]:
dict.keys()

dict_keys(['b', 'count'])

In [0]:
dict.values()

dict_values([['a1', 'a2', 'a3'], [20, 21, 22]])

In [0]:
df=pd.DataFrame(dict)

In [0]:
df

    b  count
0  a1     20
1  a2     21
2  a3     22

In [0]:
s1=pd.Series([6,12],index=['a','b'])

In [0]:
s1

a     6
b    12
dtype: int64

In [0]:
df=pd.DataFrame(s1)

In [0]:
df

    0
a   6
b  12

In [0]:
p1=['a1','a2','a3','a4']
q1=[12,13,14,15]
r1=['g1','g2','g3','g4']

In [0]:
df1=pd.DataFrame({'players':p1,'score':q1,'title':r1})

In [0]:
df1

  players  score title
0      a1     12    g1
1      a2     13    g2
2      a3     14    g3
3      a4     15    g4

In [0]:
import pandas as pd
finds=pd.read_csv("C:\\Users\\Student\\Desktop\\data_set\\finds_1.csv")

In [0]:
finds

      Sky Airtemp Humidity    Wind Water Forecast WaterSport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2  Cloudy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes

In [0]:
type(finds)

pandas.core.frame.DataFrame

In [0]:
finds.head()

      Sky Airtemp Humidity    Wind Water Forecast WaterSport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2  Cloudy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes

In [0]:
finds.tail(2)

      Sky Airtemp Humidity    Wind Water Forecast WaterSport
2  Cloudy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes

In [0]:
finds.shape

(4, 7)

In [0]:
finds.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 7 columns):
Sky           4 non-null object
Airtemp       4 non-null object
Humidity      4 non-null object
Wind          4 non-null object
Water         4 non-null object
Forecast      4 non-null object
WaterSport    4 non-null object
dtypes: object(7)
memory usage: 152.0+ bytes

In [0]:
import pandas as pd
hd=pd.read_csv("C://Users//Student//Desktop//data_set/heartdisease.csv")

In [0]:
hd

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
1,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
2,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
3,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
4,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
5,62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3
6,57.0,0.0,4.0,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0
7,63.0,1.0,4.0,130.0,254.0,0.0,2.0,147.0,0.0,1.4,2.0,1.0,7.0,2
8,53.0,1.0,4.0,140.0,203.0,1.0,2.0,155.0,1.0,3.1,3.0,0.0,7.0,1
9,57.0,1.0,4.0,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,0
10,56.0,0.0,2.0,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,0
11,56.0,1.0,3.0,130.0,256.0,1.0,2.0,142.0,1.0,0.6,2.0,1.0,6.0,2
12,44.0,1.0,2.0,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,0
13,52.0,1.0,3.0,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,0
14,57.0,1.0,3.0,150.0,168.0,0.0,0.0,174.0,0.0,1.6,1.0,0.0,3.0,0
15,48.0,1.0,2.0,110.0,229.0,0.0,0.0,168.0,0.0,1.0,3.0,0.0,7.0,1
16,54.0,1.0,4.0,140.0,239.0,0.0,0.0,160.0,0.0,1.2,1.0,0.0,3.0,0
17,48.0,0.0,3.0,130.0,275.0,0.0,0.0,139.0,0.0,0.2,1.0,0.0,3.0,0
18,49.0,1.0,2.0,130.0,266.0,0.0,0.0,171.0,0.0,0.6,1.0,0.0,3.0,0
19,64.0,1.0,1.0,110.0,211.0,0.0,2.0,144.0,1.0,1.8,2.0,0.0,3.0,0
20,58.0,0.0,1.0,150.0,283.0,1.0,2.0,162.0,0.0,1.0,1.0,0.0,3.0,0
21,58.0,1.0,2.0,120.0,284.0,0.0,2.0,160.0,0.0,1.8,2.0,0.0,3.0,1
22,58.0,1.0,3.0,132.0,224.0,0.0,2.0,173.0,0.0,3.2,1.0,2.0,7.0,3
23,60.0,1.0,4.0,130.0,206.0,0.0,2.0,132.0,1.0,2.4,2.0,2.0,7.0,4
24,50.0,0.0,3.0,120.0,219.0,0.0,0.0,158.0,0.0,1.6,2.0,0.0,3.0,0
25,58.0,0.0,3.0,120.0,340.0,0.0,0.0,172.0,0.0,0.0,1.0,0.0,3.0,0
26,66.0,0.0,1.0,150.0,226.0,0.0,0.0,114.0,0.0,2.6,3.0,0.0,3.0,0
27,43.0,1.0,4.0,150.0,247.0,0.0,0.0,171.0,0.0,1.5,1.0,0.0,3.0,0
28,40.0,1.0,4.0,110.0,167.0,0.0,2.0,114.0,1.0,2.0,2.0,0.0,7.0,3
29,69.0,0.0,1.0,140.0,239.0,0.0,0.0,151.0,0.0,1.8,1.0,2.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,71.0,0.0,4.0,112.0,149.0,0.0,0.0,125.0,0.0,1.6,2.0,0.0,3.0,0
273,59.0,1.0,1.0,134.0,204.0,0.0,0.0,162.0,0.0,0.8,1.0,2.0,3.0,1
274,64.0,1.0,1.0,170.0,227.0,0.0,2.0,155.0,0.0,0.6,2.0,0.0,7.0,0
275,66.0,0.0,3.0,146.0,278.0,0.0,2.0,152.0,0.0,0.0,2.0,1.0,3.0,0
276,39.0,0.0,3.0,138.0,220.0,0.0,0.0,152.0,0.0,0.0,2.0,0.0,3.0,0
277,57.0,1.0,2.0,154.0,232.0,0.0,2.0,164.0,0.0,0.0,1.0,1.0,3.0,1
278,58.0,0.0,4.0,130.0,197.0,0.0,0.0,131.0,0.0,0.6,2.0,0.0,3.0,0
279,57.0,1.0,4.0,110.0,335.0,0.0,0.0,143.0,1.0,3.0,2.0,1.0,7.0,2
280,47.0,1.0,3.0,130.0,253.0,0.0,0.0,179.0,0.0,0.0,1.0,0.0,3.0,0
281,55.0,0.0,4.0,128.0,205.0,0.0,1.0,130.0,1.0,2.0,2.0,1.0,7.0,3
282,35.0,1.0,2.0,122.0,192.0,0.0,0.0,174.0,0.0,0.0,1.0,0.0,3.0,0
283,61.0,1.0,4.0,148.0,203.0,0.0,0.0,161.0,0.0,0.0,1.0,1.0,7.0,2
284,58.0,1.0,4.0,114.0,318.0,0.0,1.0,140.0,0.0,4.4,3.0,3.0,6.0,4
285,58.0,0.0,4.0,170.0,225.0,1.0,2.0,146.0,1.0,2.8,2.0,2.0,6.0,2
286,58.0,1.0,2.0,125.0,220.0,0.0,0.0,144.0,0.0,0.4,2.0,?,7.0,0
287,56.0,1.0,2.0,130.0,221.0,0.0,2.0,163.0,0.0,0.0,1.0,0.0,7.0,0
288,56.0,1.0,2.0,120.0,240.0,0.0,0.0,169.0,0.0,0.0,3.0,0.0,3.0,0
289,67.0,1.0,3.0,152.0,212.0,0.0,2.0,150.0,0.0,0.8,2.0,0.0,7.0,1
290,55.0,0.0,2.0,132.0,342.0,0.0,0.0,166.0,0.0,1.2,1.0,0.0,3.0,0
291,44.0,1.0,4.0,120.0,169.0,0.0,0.0,144.0,1.0,2.8,3.0,0.0,6.0,2
292,63.0,1.0,4.0,140.0,187.0,0.0,2.0,144.0,1.0,4.0,1.0,2.0,7.0,2
293,63.0,0.0,4.0,124.0,197.0,0.0,0.0,136.0,1.0,0.0,2.0,0.0,3.0,1
294,41.0,1.0,2.0,120.0,157.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,3.0,0
295,59.0,1.0,4.0,164.0,176.0,1.0,2.0,90.0,0.0,1.0,2.0,2.0,6.0,3
296,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
297,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
298,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
299,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
300,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
301,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [0]:
hd.head()

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
1,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
2,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
3,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
4,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0

In [0]:
hd.tail()

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
297,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
298,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
299,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
300,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
301,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0

In [0]:
hd.info(null_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 14 columns):
63.0     302 non-null float64
1.0      302 non-null float64
1.0.1    302 non-null float64
145.0    302 non-null float64
233.0    302 non-null float64
1.0.2    302 non-null float64
2.0      302 non-null float64
150.0    302 non-null float64
0.0      302 non-null float64
2.3      302 non-null float64
3.0      302 non-null float64
0.0.1    302 non-null object
6.0      302 non-null object
0        302 non-null int64
dtypes: float64(11), int64(1), object(2)
memory usage: 30.7+ KB

In [0]:
hd.mean()

63.0      54.410596
1.0        0.678808
1.0.1      3.165563
145.0    131.645695
233.0    246.738411
1.0.2      0.145695
2.0        0.986755
150.0    149.605960
0.0        0.327815
2.3        1.035430
3.0        1.596026
0          0.940397
dtype: float64

In [0]:
finds.mean

<bound method DataFrame.mean of       Sky Airtemp Humidity    Wind Water Forecast WaterSport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2  Cloudy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes>

In [0]:
hd.max()

63.0      77
1.0        1
1.0.1      4
145.0    200
233.0    564
1.0.2      1
2.0        2
150.0    202
0.0        1
2.3      6.2
3.0        3
0.0.1      ?
6.0        ?
0          4
dtype: object

In [0]:
hd.describe()

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0
count,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000
mean,54.410596,0.678808,3.165563,131.645695,246.738411,0.145695,0.986755,149.605960,0.327815,1.035430,1.596026,0.940397
std,9.040163,0.467709,0.953612,17.612202,51.856829,0.353386,0.994916,22.912959,0.470196,1.160723,0.611939,1.229384
min,29.000000,0.000000,1.000000,94.000000,126.000000,0.000000,0.000000,71.000000,0.000000,0.000000,1.000000,0.000000
25%,48.000000,0.000000,3.000000,120.000000,211.000000,0.000000,0.000000,133.250000,0.000000,0.000000,1.000000,0.000000
50%,55.500000,1.000000,3.000000,130.000000,241.500000,0.000000,0.500000,153.000000,0.000000,0.800000,2.000000,0.000000
75%,61.000000,1.000000,4.000000,140.000000,275.000000,0.000000,2.000000,166.000000,1.000000,1.600000,2.000000,2.000000
max,77.000000,1.000000,4.000000,200.000000,564.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,4.000000

In [0]:
finds=finds.rename(columns={'unnamed:1':'ac'})

In [0]:
finds

      Sky Airtemp Humidity    Wind Water Forecast WaterSport
0   Sunny    Warm   Normal  Strong  Warm     Same        Yes
1   Sunny    Warm     High  Strong  Warm     Same        Yes
2  Cloudy    Cold     High  Strong  Warm   Change         No
3   Sunny    Warm     High  Strong  Cool   Change        Yes

In [0]:
hd.iloc[:0,:10]

Empty DataFrame
Columns: [63.0, 1.0, 1.0.1, 145.0, 233.0, 1.0.2, 2.0, 150.0, 0.0, 2.3]
Index: []

In [0]:
hd.iloc[-1:,-2:]

     6.0  0
301  3.0  0

In [0]:
hd.drop(columns=['63.0'])

     1.0  1.0.1  145.0  233.0  1.0.2  2.0  150.0  0.0  2.3  3.0 0.0.1  6.0  0
0    1.0    4.0  160.0  286.0    0.0  2.0  108.0  1.0  1.5  2.0   3.0  3.0  2
1    1.0    4.0  120.0  229.0    0.0  2.0  129.0  1.0  2.6  2.0   2.0  7.0  1
2    1.0    3.0  130.0  250.0    0.0  0.0  187.0  0.0  3.5  3.0   0.0  3.0  0
3    0.0    2.0  130.0  204.0    0.0  2.0  172.0  0.0  1.4  1.0   0.0  3.0  0
4    1.0    2.0  120.0  236.0    0.0  0.0  178.0  0.0  0.8  1.0   0.0  3.0  0
5    0.0    4.0  140.0  268.0    0.0  2.0  160.0  0.0  3.6  3.0   2.0  3.0  3
6    0.0    4.0  120.0  354.0    0.0  0.0  163.0  1.0  0.6  1.0   0.0  3.0  0
7    1.0    4.0  130.0  254.0    0.0  2.0  147.0  0.0  1.4  2.0   1.0  7.0  2
8    1.0    4.0  140.0  203.0    1.0  2.0  155.0  1.0  3.1  3.0   0.0  7.0  1
9    1.0    4.0  140.0  192.0    0.0  0.0  148.0  0.0  0.4  2.0   0.0  6.0  0
10   0.0    2.0  140.0  294.0    0.0  2.0  153.0  0.0  1.3  2.0   0.0  3.0  0
11   1.0    3.0  130.0  256.0    1.0  2.0  142.0  1.0  0.6  2.0   1.0  6.0  2
12   1.0    2.0  120.0  263.0    0.0  0.0  173.0  0.0  0.0  1.0   0.0  7.0  0
13   1.0    3.0  172.0  199.0    1.0  0.0  162.0  0.0  0.5  1.0   0.0  7.0  0
14   1.0    3.0  150.0  168.0    0.0  0.0  174.0  0.0  1.6  1.0   0.0  3.0  0
15   1.0    2.0  110.0  229.0    0.0  0.0  168.0  0.0  1.0  3.0   0.0  7.0  1
16   1.0    4.0  140.0  239.0    0.0  0.0  160.0  0.0  1.2  1.0   0.0  3.0  0
17   0.0    3.0  130.0  275.0    0.0  0.0  139.0  0.0  0.2  1.0   0.0  3.0  0
18   1.0    2.0  130.0  266.0    0.0  0.0  171.0  0.0  0.6  1.0   0.0  3.0  0
19   1.0    1.0  110.0  211.0    0.0  2.0  144.0  1.0  1.8  2.0   0.0  3.0  0
20   0.0    1.0  150.0  283.0    1.0  2.0  162.0  0.0  1.0  1.0   0.0  3.0  0
21   1.0    2.0  120.0  284.0    0.0  2.0  160.0  0.0  1.8  2.0   0.0  3.0  1
22   1.0    3.0  132.0  224.0    0.0  2.0  173.0  0.0  3.2  1.0   2.0  7.0  3
23   1.0    4.0  130.0  206.0    0.0  2.0  132.0  1.0  2.4  2.0   2.0  7.0  4
24   0.0    3.0  120.0  219.0    0.0  0.0  158.0  0.0  1.6  2.0   0.0  3.0  0
25   0.0    3.0  120.0  340.0    0.0  0.0  172.0  0.0  0.0  1.0   0.0  3.0  0
26   0.0    1.0  150.0  226.0    0.0  0.0  114.0  0.0  2.6  3.0   0.0  3.0  0
27   1.0    4.0  150.0  247.0    0.0  0.0  171.0  0.0  1.5  1.0   0.0  3.0  0
28   1.0    4.0  110.0  167.0    0.0  2.0  114.0  1.0  2.0  2.0   0.0  7.0  3
29   0.0    1.0  140.0  239.0    0.0  0.0  151.0  0.0  1.8  1.0   2.0  3.0  0
..   ...    ...    ...    ...    ...  ...    ...  ...  ...  ...   ...  ... ..
272  0.0    4.0  112.0  149.0    0.0  0.0  125.0  0.0  1.6  2.0   0.0  3.0  0
273  1.0    1.0  134.0  204.0    0.0  0.0  162.0  0.0  0.8  1.0   2.0  3.0  1
274  1.0    1.0  170.0  227.0    0.0  2.0  155.0  0.0  0.6  2.0   0.0  7.0  0
275  0.0    3.0  146.0  278.0    0.0  2.0  152.0  0.0  0.0  2.0   1.0  3.0  0
276  0.0    3.0  138.0  220.0    0.0  0.0  152.0  0.0  0.0  2.0   0.0  3.0  0
277  1.0    2.0  154.0  232.0    0.0  2.0  164.0  0.0  0.0  1.0   1.0  3.0  1
278  0.0    4.0  130.0  197.0    0.0  0.0  131.0  0.0  0.6  2.0   0.0  3.0  0
279  1.0    4.0  110.0  335.0    0.0  0.0  143.0  1.0  3.0  2.0   1.0  7.0  2
280  1.0    3.0  130.0  253.0    0.0  0.0  179.0  0.0  0.0  1.0   0.0  3.0  0
281  0.0    4.0  128.0  205.0    0.0  1.0  130.0  1.0  2.0  2.0   1.0  7.0  3
282  1.0    2.0  122.0  192.0    0.0  0.0  174.0  0.0  0.0  1.0   0.0  3.0  0
283  1.0    4.0  148.0  203.0    0.0  0.0  161.0  0.0  0.0  1.0   1.0  7.0  2
284  1.0    4.0  114.0  318.0    0.0  1.0  140.0  0.0  4.4  3.0   3.0  6.0  4
285  0.0    4.0  170.0  225.0    1.0  2.0  146.0  1.0  2.8  2.0   2.0  6.0  2
286  1.0    2.0  125.0  220.0    0.0  0.0  144.0  0.0  0.4  2.0     ?  7.0  0
287  1.0    2.0  130.0  221.0    0.0  2.0  163.0  0.0  0.0  1.0   0.0  7.0  0
288  1.0    2.0  120.0  240.0    0.0  0.0  169.0  0.0  0.0  3.0   0.0  3.0  0
289  1.0    3.0  152.0  212.0    0.0  2.0  150.0  0.0  0.8  2.0   0.0  7.0  1
290  0.0    2.0  132.0  342.0    0.0  0.0  166.0  0.0  1.2  1.0   0.0  3.0  0
291  1.0    4.0  120.0  169.0    0.0  0.0  144.0  1.0  2.8  3.0   0.0  6.0  2
292  1.0    4.0  140.0  187.0    0.0  2.0  144.0  1.0  4.0  1.0   2.0  7.0  2
293  0.0    4.0  124.0  197.0    0.0  0.0  136.0  1.0  0.0  2.0   0.0  3.0  1
294  1.0    2.0  120.0  157.0    0.0  0.0  182.0  0.0  0.0  1.0   0.0  3.0  0
295  1.0    4.0  164.0  176.0    1.0  2.0   90.0  0.0  1.0  2.0   2.0  6.0  3
296  0.0    4.0  140.0  241.0    0.0  0.0  123.0  1.0  0.2  2.0   0.0  7.0  1
297  1.0    1.0  110.0  264.0    0.0  0.0  132.0  0.0  1.2  2.0   0.0  7.0  1
298  1.0    4.0  144.0  193.0    1.0  0.0  141.0  0.0  3.4  2.0   2.0  7.0  2
299  1.0    4.0  130.0  131.0    0.0  0.0  115.0  1.0  1.2  2.0   1.0  7.0  3
300  0.0    2.0  130.0  236.0    0.0  2.0  174.0  0.0  0.0  2.0   1.0  3.0  1
301  1.0    3.0  138.0  175.0    0.0  0.0  173.0  0.0  0.0  1.0     ?  3.0  0

[302 rows x 13 columns]

In [0]:
hd.drop(2)

,63.0,1.0,1.0.1,145.0,233.0,1.0.2,2.0,150.0,0.0,2.3,3.0,0.0.1,6.0,0
0,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
1,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
4,56.0,1.0,2.0,120.0,236.0,0.0,0.0,178.0,0.0,0.8,1.0,0.0,3.0,0
5,62.0,0.0,4.0,140.0,268.0,0.0,2.0,160.0,0.0,3.6,3.0,2.0,3.0,3
6,57.0,0.0,4.0,120.0,354.0,0.0,0.0,163.0,1.0,0.6,1.0,0.0,3.0,0
7,63.0,1.0,4.0,130.0,254.0,0.0,2.0,147.0,0.0,1.4,2.0,1.0,7.0,2
8,53.0,1.0,4.0,140.0,203.0,1.0,2.0,155.0,1.0,3.1,3.0,0.0,7.0,1
9,57.0,1.0,4.0,140.0,192.0,0.0,0.0,148.0,0.0,0.4,2.0,0.0,6.0,0
10,56.0,0.0,2.0,140.0,294.0,0.0,2.0,153.0,0.0,1.3,2.0,0.0,3.0,0
11,56.0,1.0,3.0,130.0,256.0,1.0,2.0,142.0,1.0,0.6,2.0,1.0,6.0,2
12,44.0,1.0,2.0,120.0,263.0,0.0,0.0,173.0,0.0,0.0,1.0,0.0,7.0,0
13,52.0,1.0,3.0,172.0,199.0,1.0,0.0,162.0,0.0,0.5,1.0,0.0,7.0,0
14,57.0,1.0,3.0,150.0,168.0,0.0,0.0,174.0,0.0,1.6,1.0,0.0,3.0,0
15,48.0,1.0,2.0,110.0,229.0,0.0,0.0,168.0,0.0,1.0,3.0,0.0,7.0,1
16,54.0,1.0,4.0,140.0,239.0,0.0,0.0,160.0,0.0,1.2,1.0,0.0,3.0,0
17,48.0,0.0,3.0,130.0,275.0,0.0,0.0,139.0,0.0,0.2,1.0,0.0,3.0,0
18,49.0,1.0,2.0,130.0,266.0,0.0,0.0,171.0,0.0,0.6,1.0,0.0,3.0,0
19,64.0,1.0,1.0,110.0,211.0,0.0,2.0,144.0,1.0,1.8,2.0,0.0,3.0,0
20,58.0,0.0,1.0,150.0,283.0,1.0,2.0,162.0,0.0,1.0,1.0,0.0,3.0,0
21,58.0,1.0,2.0,120.0,284.0,0.0,2.0,160.0,0.0,1.8,2.0,0.0,3.0,1
22,58.0,1.0,3.0,132.0,224.0,0.0,2.0,173.0,0.0,3.2,1.0,2.0,7.0,3
23,60.0,1.0,4.0,130.0,206.0,0.0,2.0,132.0,1.0,2.4,2.0,2.0,7.0,4
24,50.0,0.0,3.0,120.0,219.0,0.0,0.0,158.0,0.0,1.6,2.0,0.0,3.0,0
25,58.0,0.0,3.0,120.0,340.0,0.0,0.0,172.0,0.0,0.0,1.0,0.0,3.0,0
26,66.0,0.0,1.0,150.0,226.0,0.0,0.0,114.0,0.0,2.6,3.0,0.0,3.0,0
27,43.0,1.0,4.0,150.0,247.0,0.0,0.0,171.0,0.0,1.5,1.0,0.0,3.0,0
28,40.0,1.0,4.0,110.0,167.0,0.0,2.0,114.0,1.0,2.0,2.0,0.0,7.0,3
29,69.0,0.0,1.0,140.0,239.0,0.0,0.0,151.0,0.0,1.8,1.0,2.0,3.0,0
30,60.0,1.0,4.0,117.0,230.0,1.0,0.0,160.0,1.0,1.4,1.0,2.0,7.0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
272,71.0,0.0,4.0,112.0,149.0,0.0,0.0,125.0,0.0,1.6,2.0,0.0,3.0,0
273,59.0,1.0,1.0,134.0,204.0,0.0,0.0,162.0,0.0,0.8,1.0,2.0,3.0,1
274,64.0,1.0,1.0,170.0,227.0,0.0,2.0,155.0,0.0,0.6,2.0,0.0,7.0,0
275,66.0,0.0,3.0,146.0,278.0,0.0,2.0,152.0,0.0,0.0,2.0,1.0,3.0,0
276,39.0,0.0,3.0,138.0,220.0,0.0,0.0,152.0,0.0,0.0,2.0,0.0,3.0,0
277,57.0,1.0,2.0,154.0,232.0,0.0,2.0,164.0,0.0,0.0,1.0,1.0,3.0,1
278,58.0,0.0,4.0,130.0,197.0,0.0,0.0,131.0,0.0,0.6,2.0,0.0,3.0,0
279,57.0,1.0,4.0,110.0,335.0,0.0,0.0,143.0,1.0,3.0,2.0,1.0,7.0,2
280,47.0,1.0,3.0,130.0,253.0,0.0,0.0,179.0,0.0,0.0,1.0,0.0,3.0,0
281,55.0,0.0,4.0,128.0,205.0,0.0,1.0,130.0,1.0,2.0,2.0,1.0,7.0,3
282,35.0,1.0,2.0,122.0,192.0,0.0,0.0,174.0,0.0,0.0,1.0,0.0,3.0,0
283,61.0,1.0,4.0,148.0,203.0,0.0,0.0,161.0,0.0,0.0,1.0,1.0,7.0,2
284,58.0,1.0,4.0,114.0,318.0,0.0,1.0,140.0,0.0,4.4,3.0,3.0,6.0,4
285,58.0,0.0,4.0,170.0,225.0,1.0,2.0,146.0,1.0,2.8,2.0,2.0,6.0,2
286,58.0,1.0,2.0,125.0,220.0,0.0,0.0,144.0,0.0,0.4,2.0,?,7.0,0
287,56.0,1.0,2.0,130.0,221.0,0.0,2.0,163.0,0.0,0.0,1.0,0.0,7.0,0
288,56.0,1.0,2.0,120.0,240.0,0.0,0.0,169.0,0.0,0.0,3.0,0.0,3.0,0
289,67.0,1.0,3.0,152.0,212.0,0.0,2.0,150.0,0.0,0.8,2.0,0.0,7.0,1
290,55.0,0.0,2.0,132.0,342.0,0.0,0.0,166.0,0.0,1.2,1.0,0.0,3.0,0
291,44.0,1.0,4.0,120.0,169.0,0.0,0.0,144.0,1.0,2.8,3.0,0.0,6.0,2
292,63.0,1.0,4.0,140.0,187.0,0.0,2.0,144.0,1.0,4.0,1.0,2.0,7.0,2
293,63.0,0.0,4.0,124.0,197.0,0.0,0.0,136.0,1.0,0.0,2.0,0.0,3.0,1
294,41.0,1.0,2.0,120.0,157.0,0.0,0.0,182.0,0.0,0.0,1.0,0.0,3.0,0
295,59.0,1.0,4.0,164.0,176.0,1.0,2.0,90.0,0.0,1.0,2.0,2.0,6.0,3
296,57.0,0.0,4.0,140.0,241.0,0.0,0.0,123.0,1.0,0.2,2.0,0.0,7.0,1
297,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
298,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
299,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
300,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
301,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,?,3.0,0